---
type: map
mapping:
    # Global configuration of computing nodes.
    "images":
        type: map
        mapping:
            "default":
                type: str
                required: true
            "=":
                type: str
    "network":
        type: str
        required: true
    "secgroups":
        type: seq
        required: true
        sequence:
            - type: str
    "sshkey":
        type: str
        required: true
    "pubkeys":
        type: seq
        sequence:
            - type: str
    "graceful":
        type: bool
        required: true
    # Inventory.
    "nodes_inventory":
        type: map
        matching-rule: all
        mapping:
            regex;([a-z][0-9].*):
                type: int
    # Resource group definitions.
    "deployment":
        type: map
        mapping:
            "=":
                type: map
                mapping:
                    "count":
                        type: int
                        required: true
                        range:
                            min: 0
                    "flavor":
                        type: str
                        required: true
                        enum:
                            - c1.c28m225d50
                            - c1.c28m475d50
                            - c1.c36m100d50
                            - c1.c36m225d50
                            - c1.c36m900d50
                            - c1.c36m975d50
                            - c1.c60m1975d50
                            - c1.c120m225d50
                            - c1.c120m425d50
                            - c1.c125m425d50
                            - c1.c28m935d50
                            - c1.c28m875d50
                            - g1.c14m40g1d50
                            - g1.c8m40g1d50
                            - m1.large
                            - m1.medium
                            - m1.nano
                            - m1.small
                            - m1.tiny
                            - m1.xlarge
                            - m1.xxlarge
                    "start":
                        type: date
                        format: "%Y-%m-%d"
                    "end":
                        type: date
                        format: "%Y-%m-%d"
                    "group":
                        type: str
                    "image":
                        type: str
                        required: false
                    "volume":
                        type: map
                        'mapping':
                            "size":
                                type: int
                                range:
                                    min: 12
                            "type":
                                type: str
                                enum:
                                    - default
                                    - netapp
                            "boot":
                                type: bool
                    "cgroups":
                        type: map
                        'mapping':
                            "mem_limit_policy":
                                type: str
                                enum:
                                    - soft
                                    - hard
                            "mem_reserved_size":
                                type: int
                                required: true
                                range:
                                    min: 1024
                    "docker":
                        type: bool
