---
type: map
mapping:
    "image":
        type: str
        required: true
    "image_id":
      type: str
      required: true
    "image_replace":
        type: bool
        required: true
    "network":
        type: str
        required: true
    "network_id":
        type: str
        required: true
    "secgroups":
        type: seq
        required: true
        sequence:
          - type: str
    "graceful":
        type: bool
        required: true
    "sshkey":
        type: str
        required: true
    "pubkeys":
        type: seq
        sequence:
          - type: str
    "deployment":
        type: map
        mapping:
            "=":
                type: map
                mapping:
                    "count":
                        type: int
                        required: true
                        range:
                          min: 0
                    "flavor":
                        type: str
                        required: true
                        enum:
                          - c.c10m55
                          - c.c16m120
                          - c.c40m120
                          - c.c20m120
                          - c.c32m240
                          - c.c32m250
                          - c.c40m1000
                          - c.c40m250
                          - c.c4m22
                          - c.c64m1950
                          - m1.large
                          - m1.medium
                          - m1.nano
                          - m1.small
                          - m1.tiny
                          - m1.xlarge
                          - m1.xxlarge
                          - c.c40m1000_b
                          - c1.c120m215
                          - c1.c125m425
                          - g1.gput4_g1c8m20
                    "start":
                        type: date
                        format: "%Y-%m-%d"
                    "end":
                        type: date
                        format: "%Y-%m-%d"
                    "group":
                        type: str
                    "volume":
                        type: map
                        'mapping':
                            "size":
                                type: int
                                range:
                                  min: 12
                            "type":
                                type: str
                                enum:
                                  - default
                                  - netapp
                            "boot":
                                type: bool
                    "cgroups":
                        type: bool
                    "docker_ready":
                        type: bool
                    "gpu_ready":
                        type: bool
