---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'vgcn-infrastructure'

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'vgcn-infrastructure'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install requirements.
        run: pip install -r requirements.txt

      - name: Lint code.
        run: yamllint .
  schema:
    name: Validate resource definition
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'vgcn-infrastructure'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install requirements.
        run: pip install -r requirements.txt

      - name: Validate resource definition.
        run: pykwalify -d resources.yaml -s schema.yaml
